# Generated by Django 5.0.6 on 2024-05-11 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categoria',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Producto',
        ),
    ]
