# Generated by Django 5.0.6 on 2024-05-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_producto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='product_code',
            field=models.CharField(default='1234', max_length=100),
        ),
    ]
