# Generated by Django 5.0.6 on 2024-05-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_producto_discount_percentage_producto_in_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
